# Generated by Django 4.2.7 on 2023-11-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='punch',
            new_name='punch1',
        ),
    ]
