# Generated by Django 4.2.7 on 2023-11-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punch', '0002_rename_punch_punch1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='punch1',
            old_name='EndWork',
            new_name='endWork',
        ),
        migrations.RenameField(
            model_name='punch1',
            old_name='StartWork',
            new_name='startWork',
        ),
    ]
