# Generated by Django 4.2.7 on 2023-11-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punch', '0003_rename_endwork_punch1_endwork_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch1',
            name='endWork',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='punch1',
            name='startWork',
            field=models.CharField(max_length=60),
        ),
    ]
