# Generated by Django 4.2.7 on 2023-11-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punch', '0005_alter_punch1_startwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch1',
            name='endWork',
            field=models.DateTimeField(default=models.DateTimeField(max_length=60)),
        ),
    ]
