# Generated by Django 4.2.7 on 2023-11-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punch', '0006_alter_punch1_endwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch1',
            name='endWork',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='punch1',
            name='startWork',
            field=models.DateTimeField(),
        ),
    ]
