# Generated by Django 4.2.7 on 2023-11-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Time',
            new_name='daliytime',
        ),
    ]
